---
- name: Hello World
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Say Hello
      condition: event.payload.message == "Demo EDA Astra Automation"
      action:
        debug:
          msg: "Hello World!"
